spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(dQ7qdJszchwr0VGWPSGWHp1RFRoXfuw6Y21I/8UOBTBgjWA1YHze7dGYUUbHAcL2SL7GlNISNpLYat5PalAE7HBmgNtW5vUNyJBQPUGfBPus36NRPHf9CA==)
            client-secret: ENC(EgKyVBqmiZSgXUjWXgWkMiWp3+k7J5ug6YN+3bR6sRXM66hd7nLaU34cjAqp0zG1)
            scope: profile,email,openid

cloud:
  aws:
    credentials:
      accessKey: ENC(Me/EbbBvygqh327xvKqgWZXUuRyVU7fsrKXV7vHG8fg=)
      secretKey: ENC(sV499ai524txYIancozaY70I3JEfi5KUV3DCjjSXHjCJ9ZSvOGwmnDzYDcoyJex3LEEeeeyOOHk=)

      instanceProfile : true
    s3:
      bucket: miniprojectspring7
    region:
      static: ap-northeast-2
    stack:
      auto: false


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${CUSTOMPASSWORD}
    property:
      prefix: ENC(
      suffix: )
