spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(onBa5hmUiJZ+xrwmH4odUfXu7Sleh/4fNjzcEkED1eAW/Q66HJpEOsS5K9zv8nt50ontleR6Os1rATXZ1AMd+A0qqgcFMVGbnTDywKmRsZ/2C7qIOo7SuA==)
            client-secret: ENC(EYzEhNlbWYp+hzXTbV2FD6lhxGntHiw4HTvKhBzCXBEfLADYSheEBZUjczxoHJCF)
            scope: profile,email,openid

cloud:
  aws:
    credentials:
      accessKey: ENC(Me/EbbBvygqh327xvKqgWZXUuRyVU7fsrKXV7vHG8fg=)
      secretKey: ENC(sV499ai524txYIancozaY70I3JEfi5KUV3DCjjSXHjCJ9ZSvOGwmnDzYDcoyJex3LEEeeeyOOHk=)

      instanceProfile : true
    s3:
      bucket: miniprojectspring7
    region:
      static: ap-northeast-2
    stack:
      auto: false


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${CUSTOMPASSWORD}
    property:
      prefix: ENC(
      suffix: )
