spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(cfgNZ3U1egJzPgQ95yxY1Y6MuJpowdarnpe4heDJWrP3Czu2/5EvOo0EYc7SnD+2wzMKKylDQpmpchkH3GJQI56G6WC81N3xTkjhBxpDJ4ghrOwd357PXQ==)
            client-secret: ENC(InxlKRkgpQHHrZLODQSnSTvHlTThXqo56jjDCHdjtK1Tc6A7pBOHUtK9IjC0Mkf5)
            scope: profile,email,openid

cloud:
  aws:
    credentials:
      accessKey: ENC(Me/EbbBvygqh327xvKqgWZXUuRyVU7fsrKXV7vHG8fg=)
      secretKey: ENC(sV499ai524txYIancozaY70I3JEfi5KUV3DCjjSXHjCJ9ZSvOGwmnDzYDcoyJex3LEEeeeyOOHk=)

      instanceProfile : true
    s3:
      bucket: miniprojectspring7
    region:
      static: ap-northeast-2
    stack:
      auto: false


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${CUSTOMPASSWORD}
    property:
      prefix: ENC(
      suffix: )
